// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Task struct {
	ID     uuid.UUID
	UserID uuid.NullUUID
	State  pqtype.NullRawMessage
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	Token        string
	RefreshToken string
	ExpireAt     sql.NullTime
}
