// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Context struct {
	ID          pgtype.UUID
	Name        *string
	Description *string
	Content     *string
	UserID      pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type Message struct {
	ID        pgtype.UUID
	MessageID *string
	TaskID    pgtype.UUID
	Content   *string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Read      *bool
}

type SpamEmail struct {
	ID        pgtype.UUID
	MessageID *string
	Subject   *string
	EmailBody *string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Task struct {
	ID             pgtype.UUID
	Name           string
	Description    string
	ToolDefinition *string
	Context        *string
	CreatedAt      pgtype.Timestamptz
	UserID         pgtype.UUID
	MessageID      *string
	MessageBody    *string
	ConversationID *string
	ContextIds     []pgtype.UUID
	State          []byte
}

type User struct {
	ID                   pgtype.UUID
	Name                 string
	Email                string
	Token                string
	RefreshToken         *string
	SubscriptionID       *string
	SubscriptionExpireAt pgtype.Timestamptz
	SubscriptionDisabled *bool
	ExpireAt             pgtype.Timestamptz
	CheckSpam            *bool
}
