// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID        pgtype.UUID
	MessageID *string
	TaskID    pgtype.UUID
	Content   *string
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Read      *bool
}

type Task struct {
	ID             pgtype.UUID
	Name           string
	Description    string
	CreatedAt      pgtype.Timestamptz
	UserID         pgtype.UUID
	ConversationID *string
	State          []byte
}

type User struct {
	ID                   pgtype.UUID
	Name                 string
	Email                string
	Token                string
	SubscriptionID       *string
	SubscriptionExpireAt pgtype.Timestamptz
	ExpireAt             pgtype.Timestamptz
}
