name: Build and Push Docker Images

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}  # Add this line
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            runs-on: ubuntu-latest
          - platform: linux/arm64
            runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: matrix.platform != 'darwin/amd64' && matrix.platform != 'darwin/arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/server:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}/server:latest

      - name: Build and push UI Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./ui
          file: ./ui/Dockerfile.ui
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ui:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}/ui:latest
